/* tslint:disable */
/* eslint-disable */
/**
 * Inundated
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateTimeSpan,
  TimeSpan,
  UpdateTimeSpan,
} from '../models/index';
import {
    CreateTimeSpanFromJSON,
    CreateTimeSpanToJSON,
    TimeSpanFromJSON,
    TimeSpanToJSON,
    UpdateTimeSpanFromJSON,
    UpdateTimeSpanToJSON,
} from '../models/index';

export interface CreateTimeSpanRequest {
    createTimeSpan: CreateTimeSpan;
}

export interface DeleteTimeSpanRequest {
    timeSpanId: string;
}

export interface GetTimeSpanRequest {
    timeSpanId: string;
}

export interface UpdateTimeSpanRequest {
    timeSpanId: string;
    updateTimeSpan: UpdateTimeSpan;
}

/**
 * 
 */
export class TimeSpansApi extends runtime.BaseAPI {

    /**
     * Create time span
     */
    async createTimeSpanRaw(requestParameters: CreateTimeSpanRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TimeSpan>> {
        if (requestParameters['createTimeSpan'] == null) {
            throw new runtime.RequiredError(
                'createTimeSpan',
                'Required parameter "createTimeSpan" was null or undefined when calling createTimeSpan().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/time-spans`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateTimeSpanToJSON(requestParameters['createTimeSpan']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TimeSpanFromJSON(jsonValue));
    }

    /**
     * Create time span
     */
    async createTimeSpan(requestParameters: CreateTimeSpanRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TimeSpan> {
        const response = await this.createTimeSpanRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete time span
     */
    async deleteTimeSpanRaw(requestParameters: DeleteTimeSpanRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['timeSpanId'] == null) {
            throw new runtime.RequiredError(
                'timeSpanId',
                'Required parameter "timeSpanId" was null or undefined when calling deleteTimeSpan().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/time-spans/{timeSpanId}`;
        urlPath = urlPath.replace(`{${"timeSpanId"}}`, encodeURIComponent(String(requestParameters['timeSpanId'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete time span
     */
    async deleteTimeSpan(requestParameters: DeleteTimeSpanRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteTimeSpanRaw(requestParameters, initOverrides);
    }

    /**
     * Get time span
     */
    async getTimeSpanRaw(requestParameters: GetTimeSpanRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TimeSpan>> {
        if (requestParameters['timeSpanId'] == null) {
            throw new runtime.RequiredError(
                'timeSpanId',
                'Required parameter "timeSpanId" was null or undefined when calling getTimeSpan().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/time-spans/{timeSpanId}`;
        urlPath = urlPath.replace(`{${"timeSpanId"}}`, encodeURIComponent(String(requestParameters['timeSpanId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TimeSpanFromJSON(jsonValue));
    }

    /**
     * Get time span
     */
    async getTimeSpan(requestParameters: GetTimeSpanRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TimeSpan> {
        const response = await this.getTimeSpanRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List time spans
     */
    async listTimeSpansRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<TimeSpan>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/time-spans`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(TimeSpanFromJSON));
    }

    /**
     * List time spans
     */
    async listTimeSpans(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<TimeSpan>> {
        const response = await this.listTimeSpansRaw(initOverrides);
        return await response.value();
    }

    /**
     * Update time span
     */
    async updateTimeSpanRaw(requestParameters: UpdateTimeSpanRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TimeSpan>> {
        if (requestParameters['timeSpanId'] == null) {
            throw new runtime.RequiredError(
                'timeSpanId',
                'Required parameter "timeSpanId" was null or undefined when calling updateTimeSpan().'
            );
        }

        if (requestParameters['updateTimeSpan'] == null) {
            throw new runtime.RequiredError(
                'updateTimeSpan',
                'Required parameter "updateTimeSpan" was null or undefined when calling updateTimeSpan().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/time-spans/{timeSpanId}`;
        urlPath = urlPath.replace(`{${"timeSpanId"}}`, encodeURIComponent(String(requestParameters['timeSpanId'])));

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateTimeSpanToJSON(requestParameters['updateTimeSpan']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TimeSpanFromJSON(jsonValue));
    }

    /**
     * Update time span
     */
    async updateTimeSpan(requestParameters: UpdateTimeSpanRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TimeSpan> {
        const response = await this.updateTimeSpanRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
