/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ColorInput: typeof import('./src/components/inputs/ColorInput.vue')['default']
    ConfirmationPopup: typeof import('./src/components/inputs/ConfirmationPopup.vue')['default']
    MaterialIcon: typeof import('./src/components/icons/MaterialIcon.vue')['default']
    ProjectEdit: typeof import('./src/components/project/ProjectEdit.vue')['default']
    ProjectStats: typeof import('./src/components/project/ProjectStats.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBox: typeof import('./src/components/inputs/SearchBox.vue')['default']
    TagEdit: typeof import('./src/components/tags/TagEdit.vue')['default']
    TagItem: typeof import('./src/components/tags/TagItem.vue')['default']
    TagListEmbedded: typeof import('./src/components/tags/TagListEmbedded.vue')['default']
    TheMenu: typeof import('./src/components/TheMenu.vue')['default']
    TheTimesheet: typeof import('./src/components/timesheet/TheTimesheet.vue')['default']
    TimeInput: typeof import('./src/components/inputs/TimeInput.vue')['default']
    TimesheetItem: typeof import('./src/components/timesheet/TimesheetItem.vue')['default']
    TimespanEdit: typeof import('./src/components/inputs/TimespanEdit.vue')['default']
  }
}
