# yaml-language-server: $schema=https://spec.openapis.org/oas/3.1/schema/2025-09-15
openapi: 3.1.2
info:
  title: Inundated
  version: 0.1.0
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
servers:
  - url: /api
tags:
  - name: tags
    description: Tag-related operations
  - name: projects
    description: Project-related operations
  - name: timespans
    description: Timespan-related operations
paths:
  /tags:
    $ref: "./paths/tags.yaml#/tags"
  /tags/{tagId}:
    $ref: "./paths/tags.yaml#/tags-id"
  /projects:
    $ref: "./paths/projects.yaml#/projects"
  /projects/{projectId}:
    $ref: "./paths/projects.yaml#/projects-id"
  /timespans:
    $ref: "./paths/timespans.yaml#/timespans"
  /timespans/{timespanId}:
    $ref: "./paths/timespans.yaml#/timespans-id"
components:
  #   securitySchemes:
  #     oidc:
  #       type: openIdConnect
  #       openIdConnectUrl: https://example.com/.well-known/openid-configuration
  schemas:
    Tag:
      $ref: "./schemas/tags.yaml#/Tag"
    CreateTag:
      $ref: "./schemas/tags.yaml#/CreateTag"
    UpdateTag:
      $ref: "./schemas/tags.yaml#/UpdateTag"
    Project:
      $ref: "./schemas/projects.yaml#/Project"
    CreateProject:
      $ref: "./schemas/projects.yaml#/CreateProject"
    UpdateProject:
      $ref: "./schemas/projects.yaml#/UpdateProject"
    Timespan:
      $ref: "./schemas/timespans.yaml#/Timespan"
    CreateTimespan:
      $ref: "./schemas/timespans.yaml#/CreateTimespan"
    UpdateTimespan:
      $ref: "./schemas/timespans.yaml#/UpdateTimespan"
