# yaml-language-server: $schema=https://spec.openapis.org/oas/3.1/schema/2025-09-15

openapi: 3.1.2
info:
  title: Inundated
  version: 0.0.1

servers:
  - url: /api

tags:
  - name: tags
  - name: projects
  - name: timeSpans

paths: {}
#   /items:
#     get:
#       tags: [items]
#       summary: List items
#       operationId: listItems
#       security:
#         - oidc: []
#       responses:
#         '200':
#           description: List of items
#           content:
#             application/json:
#               schema:
#                 type: array
#                 items:
#                   $ref: '#/components/schemas/Item'

#     post:
#       tags: [items]
#       summary: Create item
#       operationId: createItem
#       security:
#         - oidc: []
#       requestBody:
#         required: true
#         content:
#           application/json:
#             schema:
#               $ref: '#/components/schemas/CreateItem'
#       responses:
#         '201':
#           description: Item created
#           content:
#             application/json:
#               schema:
#                 $ref: '#/components/schemas/Item'

#   /items/{id}:
#     parameters:
#       - name: id
#         in: path
#         required: true
#         schema:
#           type: string
#           format: uuid

#     get:
#       tags: [items]
#       summary: Get item
#       operationId: getItem
#       security:
#         - oidc: []
#       responses:
#         '200':
#           description: Item
#           content:
#             application/json:
#               schema:
#                 $ref: '#/components/schemas/Item'
#         '404':
#           description: Not found

#     put:
#       tags: [items]
#       summary: Update item
#       operationId: updateItem
#       security:
#         - oidc: []
#       requestBody:
#         required: true
#         content:
#           application/json:
#             schema:
#               $ref: '#/components/schemas/UpdateItem'
#       responses:
#         '200':
#           description: Updated item
#           content:
#             application/json:
#               schema:
#                 $ref: '#/components/schemas/Item'

#     delete:
#       tags: [items]
#       summary: Delete item
#       operationId: deleteItem
#       security:
#         - oidc: []
#       responses:
#         '204':
#           description: Deleted

components:
#   securitySchemes:
#     oidc:
#       type: openIdConnect
#       openIdConnectUrl: https://example.com/.well-known/openid-configuration

  schemas:
    Tag:
      type: object
      required: [id, name, color]
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
          minLength: 1
        color:
          type: string
          pattern: '^#[0-9a-f]{6}$'
    CreateTag:
      type: object
      required: [name, color]
      properties:
        name:
          type: string
          minLength: 1
        color:
          type: string
          pattern: '^#[0-9a-f]{6}$'
    UpdateTag:
      type: object
      minProperties: 1
      properties:
        name:
          type: string
          minLength: 1
        color:
          type: string
          pattern: '^#[0-9a-f]{6}$'
    Project:
      type: object
      required: [id, name, color, timeBudget, tagIds]
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
          minLength: 1
        color:
          type: string
          pattern: '^#[0-9a-f]{6}$'
        timeBudget:
          type: number
          format: double
        tagIds:
          type: array
          uniqueItems: true
          items:
            type: string
            format: uuid
    CreateProject:
      type: object
      required: [name, color]
      properties:
        name:
          type: string
          minLength: 1
        color:
          type: string
          pattern: '^#[0-9a-f]{6}$'
        timeBudget:
          type: number
          format: double
        tagIds:
          type: array
          uniqueItems: true
          items:
            type: string
            format: uuid
    UpdateProject:
      type: object
      minProperties: 1
      properties:
        name:
          type: string
          minLength: 1
        color:
          type: string
          pattern: '^#[0-9a-f]{6}$'
        timeBudget:
          type: number
          format: double
        tagIds:
          type: array
          uniqueItems: true
          items:
            type: string
            format: uuid
    TimeSpan:
      type: object
      required: [id, name, startTime, endTime]
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
          minLength: 1
        startTime:
          type: string
          format: date-time
        endTime:
          type: string
          format: date-time
    CreateTimeSpan:
      type: object
      required: [name, startTime, endTime]
      properties:
        name:
          type: string
          minLength: 1
        startTime:
          type: string
          format: date-time
        endTime:
          type: string
          format: date-time
    UpdateTimeSpan:
      type: object
      minProperties: 1
      properties:
        name:
          type: string
          minLength: 1
        startTime:
          type: string
          format: date-time
        endTime:
          type: string
          format: date-time
