# yaml-language-server: $schema=https://spec.openapis.org/oas/3.1/schema/2025-09-15
openapi: 3.1.2
info:
  title: Inundated
  version: 0.1.0
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
servers:
  - url: /
security:
  - sessionCookie: []
tags:
  - name: users
    description: User-related operations
  - name: tags
    description: Tag-related operations
  - name: projects
    description: Project-related operations
  - name: timespans
    description: Timespan-related operations
paths:
  /auth/login:
    $ref: "./paths/auth.yaml#/login"
  /auth/callback:
    $ref: "./paths/auth.yaml#/callback"
  /auth/logout:
    $ref: "./paths/auth.yaml#/logout"

  /api/me:
    $ref: "./paths/users.yaml#/me"
  /api/tags:
    $ref: "./paths/tags.yaml#/tags"
  /api/tags/{tagId}:
    $ref: "./paths/tags.yaml#/tags-id"
  /api/projects:
    $ref: "./paths/projects.yaml#/projects"
  /api/projects/{projectId}:
    $ref: "./paths/projects.yaml#/projects-id"
  /api/projects/{projectId}/stats:
    $ref: "./paths/projects.yaml#/projects-id-stats"
  /api/timespans:
    $ref: "./paths/timespans.yaml#/timespans"
  /api/timespans/{timespanId}:
    $ref: "./paths/timespans.yaml#/timespans-id"
components:
  securitySchemes:
    sessionCookie:
      type: apiKey
      in: cookie
      name: session
  schemas:
    User:
      $ref: "./schemas/users.yaml#/User"
    UpdateUser:
      $ref: "./schemas/users.yaml#/UpdateUser"
    Tag:
      $ref: "./schemas/tags.yaml#/Tag"
    CreateTag:
      $ref: "./schemas/tags.yaml#/CreateTag"
    UpdateTag:
      $ref: "./schemas/tags.yaml#/UpdateTag"
    Project:
      $ref: "./schemas/projects.yaml#/Project"
    CreateProject:
      $ref: "./schemas/projects.yaml#/CreateProject"
    UpdateProject:
      $ref: "./schemas/projects.yaml#/UpdateProject"
    Timespan:
      $ref: "./schemas/timespans.yaml#/Timespan"
    CreateTimespan:
      $ref: "./schemas/timespans.yaml#/CreateTimespan"
    UpdateTimespan:
      $ref: "./schemas/timespans.yaml#/UpdateTimespan"
