// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

// CreateProject defines model for CreateProject.
type CreateProject struct {
	Color      string                `json:"color"`
	Name       string                `json:"name"`
	TagIds     *[]openapi_types.UUID `json:"tagIds,omitempty"`
	TimeBudget *float64              `json:"timeBudget,omitempty"`
}

// CreateTag defines model for CreateTag.
type CreateTag struct {
	Color string `json:"color"`
	Name  string `json:"name"`
}

// CreateTimeSpan defines model for CreateTimeSpan.
type CreateTimeSpan struct {
	EndTime   time.Time `json:"endTime"`
	Name      string    `json:"name"`
	StartTime time.Time `json:"startTime"`
}

// Project defines model for Project.
type Project struct {
	Color      string               `json:"color"`
	Id         openapi_types.UUID   `json:"id"`
	Name       string               `json:"name"`
	TagIds     []openapi_types.UUID `json:"tagIds"`
	TimeBudget float64              `json:"timeBudget"`
}

// Tag defines model for Tag.
type Tag struct {
	Color string             `json:"color"`
	Id    openapi_types.UUID `json:"id"`
	Name  string             `json:"name"`
}

// TimeSpan defines model for TimeSpan.
type TimeSpan struct {
	EndTime   time.Time          `json:"endTime"`
	Id        openapi_types.UUID `json:"id"`
	Name      string             `json:"name"`
	StartTime time.Time          `json:"startTime"`
}

// UpdateProject defines model for UpdateProject.
type UpdateProject struct {
	Color      *string               `json:"color,omitempty"`
	Name       *string               `json:"name,omitempty"`
	TagIds     *[]openapi_types.UUID `json:"tagIds,omitempty"`
	TimeBudget *float64              `json:"timeBudget,omitempty"`
}

// UpdateTag defines model for UpdateTag.
type UpdateTag struct {
	Color *string `json:"color,omitempty"`
	Name  *string `json:"name,omitempty"`
}

// UpdateTimeSpan defines model for UpdateTimeSpan.
type UpdateTimeSpan struct {
	EndTime   *time.Time `json:"endTime,omitempty"`
	Name      *string    `json:"name,omitempty"`
	StartTime *time.Time `json:"startTime,omitempty"`
}

// CreateProjectJSONRequestBody defines body for CreateProject for application/json ContentType.
type CreateProjectJSONRequestBody = CreateProject

// UpdateProjectJSONRequestBody defines body for UpdateProject for application/json ContentType.
type UpdateProjectJSONRequestBody = UpdateProject

// CreateTagJSONRequestBody defines body for CreateTag for application/json ContentType.
type CreateTagJSONRequestBody = CreateTag

// UpdateTagJSONRequestBody defines body for UpdateTag for application/json ContentType.
type UpdateTagJSONRequestBody = UpdateTag

// CreateTimeSpanJSONRequestBody defines body for CreateTimeSpan for application/json ContentType.
type CreateTimeSpanJSONRequestBody = CreateTimeSpan

// UpdateTimeSpanJSONRequestBody defines body for UpdateTimeSpan for application/json ContentType.
type UpdateTimeSpanJSONRequestBody = UpdateTimeSpan
