// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	SessionCookieScopes = "sessionCookie.Scopes"
)

// Defines values for ProjectStatsMetric.
const (
	ProjectStatsMetricTimeSpent ProjectStatsMetric = "time_spent"
)

// Defines values for ProjectStatsMetrics.
const (
	ProjectStatsMetricsTimeSpent ProjectStatsMetrics = "time_spent"
)

// Defines values for GetProjectParamsInclude.
const (
	GetProjectParamsIncludeTotalTimeMs GetProjectParamsInclude = "totalTimeMs"
)

// Defines values for GetProjectStatsParamsMetric.
const (
	TimeSpent GetProjectStatsParamsMetric = "time_spent"
)

// Defines values for GetTagParamsInclude.
const (
	GetTagParamsIncludeTotalTimeMs GetTagParamsInclude = "totalTimeMs"
)

// CreateProject defines model for CreateProject.
type CreateProject struct {
	Color           HexColor   `json:"color"`
	Name            string     `json:"name"`
	TagIds          *TagIdList `json:"tagIds,omitempty"`
	TimeBudgetHours *float64   `json:"timeBudgetHours,omitempty"`
}

// CreateTag defines model for CreateTag.
type CreateTag struct {
	Color HexColor `json:"color"`
	Name  string   `json:"name"`
}

// CreateTimespan defines model for CreateTimespan.
type CreateTimespan struct {
	EndTime   time.Time  `json:"endTime"`
	Name      *string    `json:"name,omitempty"`
	StartTime time.Time  `json:"startTime"`
	TagIds    *TagIdList `json:"tagIds,omitempty"`
}

// HexColor defines model for HexColor.
type HexColor = string

// Location defines model for Location.
type Location = string

// PaginatedProjects defines model for PaginatedProjects.
type PaginatedProjects struct {
	// Data Array of items in this page
	Data []Project `json:"data"`

	// Pagination Pagination metadata
	Pagination PaginationDetails `json:"pagination"`
}

// PaginatedTags defines model for PaginatedTags.
type PaginatedTags struct {
	// Data Array of items in this page
	Data []Tag `json:"data"`

	// Pagination Pagination metadata
	Pagination PaginationDetails `json:"pagination"`
}

// PaginatedTimespans defines model for PaginatedTimespans.
type PaginatedTimespans struct {
	// Data Array of items in this page
	Data []Timespan `json:"data"`

	// Pagination Pagination metadata
	Pagination PaginationDetails `json:"pagination"`
}

// PaginationDetails Pagination metadata
type PaginationDetails struct {
	// Limit Items per page
	Limit int `json:"limit"`

	// Offset Number of items skipped
	Offset int `json:"offset"`

	// Total Total number of items available
	Total int `json:"total"`
}

// Project defines model for Project.
type Project struct {
	Color           HexColor           `json:"color"`
	Id              openapi_types.UUID `json:"id"`
	Name            string             `json:"name"`
	TagIds          *TagIdList         `json:"tagIds,omitempty"`
	TimeBudgetHours *float64           `json:"timeBudgetHours,omitempty"`
	TotalTimeMs     *int               `json:"totalTimeMs,omitempty"`
}

// ProjectStats defines model for ProjectStats.
type ProjectStats struct {
	// Granularity The ISO 8601 duration used to bucket each series point.
	Granularity string `json:"granularity"`

	// Interval The effective time range of the response as an ISO 8601 interval, always resolved to `{start}/{end}` form regardless of how the request was expressed.
	Interval string `json:"interval"`

	// Metric The metric that was aggregated.
	Metric ProjectStatsMetric `json:"metric"`

	// ProjectId The ID of the project this data belongs to.
	ProjectId openapi_types.UUID `json:"project_id"`

	// Series Ordered list of aggregated data points.
	Series []SeriesPoint `json:"series"`

	// Unit The unit of the `value` field in each series point. Allows clients to label axes correctly without hardcoding.
	Unit string `json:"unit"`
}

// ProjectStatsMetric The metric that was aggregated.
type ProjectStatsMetric string

// SeriesPoint defines model for SeriesPoint.
type SeriesPoint struct {
	// Interval The time bucket for this data point as an ISO 8601 interval in `{start}/{end}` form (e.g. `2024-01-01T00:00:00Z/2024-01-08T00:00:00Z`).
	Interval string `json:"interval"`

	// Value The aggregated metric value for this bucket.
	Value float32 `json:"value"`
}

// Tag defines model for Tag.
type Tag struct {
	Color       HexColor           `json:"color"`
	Id          openapi_types.UUID `json:"id"`
	Name        string             `json:"name"`
	TotalTimeMs *int               `json:"totalTimeMs,omitempty"`
}

// TagIdList defines model for TagIdList.
type TagIdList = []openapi_types.UUID

// Timespan defines model for Timespan.
type Timespan struct {
	EndTime   time.Time          `json:"endTime"`
	Id        openapi_types.UUID `json:"id"`
	Name      *string            `json:"name,omitempty"`
	StartTime time.Time          `json:"startTime"`
	TagIds    *TagIdList         `json:"tagIds,omitempty"`
}

// UpdateProject defines model for UpdateProject.
type UpdateProject struct {
	Color           *HexColor  `json:"color,omitempty"`
	Name            *string    `json:"name,omitempty"`
	TagIds          *TagIdList `json:"tagIds,omitempty"`
	TimeBudgetHours *float64   `json:"timeBudgetHours,omitempty"`
}

// UpdateTag defines model for UpdateTag.
type UpdateTag struct {
	Color *HexColor `json:"color,omitempty"`
	Name  *string   `json:"name,omitempty"`
}

// UpdateTimespan defines model for UpdateTimespan.
type UpdateTimespan struct {
	EndTime   *time.Time `json:"endTime,omitempty"`
	Name      *string    `json:"name,omitempty"`
	StartTime *time.Time `json:"startTime,omitempty"`
	TagIds    *TagIdList `json:"tagIds,omitempty"`
}

// UpdateUser defines model for UpdateUser.
type UpdateUser struct {
	// Email Email address
	Email *openapi_types.Email `json:"email,omitempty"`

	// Name Display name
	Name *string `json:"name,omitempty"`
}

// User defines model for User.
type User struct {
	// Email Email from OIDC token
	Email openapi_types.Email `json:"email"`

	// Id Internal unique identifier for this user
	Id openapi_types.UUID `json:"id"`

	// Name Display name from OIDC token
	Name *string `json:"name,omitempty"`

	// Sub OIDC subject claim (unique per provider, immutable identifier)
	Sub string `json:"sub"`
}

// XSRFTokenHeader defines model for XSRFTokenHeader.
type XSRFTokenHeader = string

// Code defines model for code.
type Code = string

// Granularity defines model for granularity.
type Granularity = string

// IncludeQuery defines model for includeQuery.
type IncludeQuery = []string

// Interval defines model for interval.
type Interval = string

// Limit defines model for limit.
type Limit = int

// Offset defines model for offset.
type Offset = int

// ProjectIdPath defines model for projectIdPath.
type ProjectIdPath = openapi_types.UUID

// ProjectStatsMetrics defines model for projectStatsMetrics.
type ProjectStatsMetrics string

// Redirect defines model for redirect.
type Redirect = string

// State defines model for state.
type State = string

// TagIdPath defines model for tagIdPath.
type TagIdPath = openapi_types.UUID

// TimespanIdPath defines model for timespanIdPath.
type TimespanIdPath = openapi_types.UUID

// Timezone defines model for timezone.
type Timezone = string

// UpdateCurrentUserParams defines parameters for UpdateCurrentUser.
type UpdateCurrentUserParams struct {
	// XXSRFTOKEN Anti-CSRF token extracted from the XSRF-TOKEN cookie.
	XXSRFTOKEN XSRFTokenHeader `json:"X-XSRF-TOKEN"`
}

// ListProjectsParams defines parameters for ListProjects.
type ListProjectsParams struct {
	// Limit Maximum number of items to return per page. Capped at 100 to prevent resource exhaustion.
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Number of items to skip from the beginning (zero-indexed).
	Offset *Offset `form:"offset,omitempty" json:"offset,omitempty"`
}

// CreateProjectParams defines parameters for CreateProject.
type CreateProjectParams struct {
	// XXSRFTOKEN Anti-CSRF token extracted from the XSRF-TOKEN cookie.
	XXSRFTOKEN XSRFTokenHeader `json:"X-XSRF-TOKEN"`
}

// DeleteProjectParams defines parameters for DeleteProject.
type DeleteProjectParams struct {
	// XXSRFTOKEN Anti-CSRF token extracted from the XSRF-TOKEN cookie.
	XXSRFTOKEN XSRFTokenHeader `json:"X-XSRF-TOKEN"`
}

// GetProjectParams defines parameters for GetProject.
type GetProjectParams struct {
	// Include Comma-separated list of optional computed fields to include. Supported values: totalTimeMs
	Include *IncludeQuery `form:"include,omitempty" json:"include,omitempty"`
}

// GetProjectParamsInclude defines parameters for GetProject.
type GetProjectParamsInclude string

// UpdateProjectParams defines parameters for UpdateProject.
type UpdateProjectParams struct {
	// XXSRFTOKEN Anti-CSRF token extracted from the XSRF-TOKEN cookie.
	XXSRFTOKEN XSRFTokenHeader `json:"X-XSRF-TOKEN"`
}

// GetProjectStatsParams defines parameters for GetProjectStats.
type GetProjectStatsParams struct {
	// Metric The metric to aggregate over time.
	Metric GetProjectStatsParamsMetric `form:"metric" json:"metric"`

	// Interval The time range to query as an ISO 8601 interval. Supports all three forms:
	// - `{start}/{end}` — explicit start and end datetimes: `2024-01-01T00:00:00Z/2024-03-31T23:59:59Z` - `{start}/{duration}` — start datetime and a duration: `2024-01-01T00:00:00Z/P3M` - `{duration}/{end}` — a duration ending at a datetime: `P30D/2024-03-31T23:59:59Z`
	// Datetime values must be full RFC 3339 timestamps including timezone (for example `...Z` or `...+01:00`). Duration/duration intervals are not supported.
	// Defaults to `P30D/{now}` (the last 30 days) if omitted.
	Interval *Interval `form:"interval,omitempty" json:"interval,omitempty"`

	// Granularity The bucket size for each data point, expressed as an ISO 8601 duration. Common values: `PT1M` (minute), `PT1H` (hour), `P1D` (day), `P1W` (week), `P1M` (month). Defaults to `P1D`.
	Granularity *Granularity `form:"granularity,omitempty" json:"granularity,omitempty"`

	// Timezone IANA timezone used for bucketing (e.g. `Europe/Stockholm`). Defaults to UTC. Affects how day/week/month boundaries are computed.
	Timezone *Timezone `form:"timezone,omitempty" json:"timezone,omitempty"`
}

// GetProjectStatsParamsMetric defines parameters for GetProjectStats.
type GetProjectStatsParamsMetric string

// ListTagsParams defines parameters for ListTags.
type ListTagsParams struct {
	// Limit Maximum number of items to return per page. Capped at 100 to prevent resource exhaustion.
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Number of items to skip from the beginning (zero-indexed).
	Offset *Offset `form:"offset,omitempty" json:"offset,omitempty"`
}

// CreateTagParams defines parameters for CreateTag.
type CreateTagParams struct {
	// XXSRFTOKEN Anti-CSRF token extracted from the XSRF-TOKEN cookie.
	XXSRFTOKEN XSRFTokenHeader `json:"X-XSRF-TOKEN"`
}

// DeleteTagParams defines parameters for DeleteTag.
type DeleteTagParams struct {
	// XXSRFTOKEN Anti-CSRF token extracted from the XSRF-TOKEN cookie.
	XXSRFTOKEN XSRFTokenHeader `json:"X-XSRF-TOKEN"`
}

// GetTagParams defines parameters for GetTag.
type GetTagParams struct {
	// Include Comma-separated list of optional computed fields to include. Supported values: totalTimeMs
	Include *IncludeQuery `form:"include,omitempty" json:"include,omitempty"`
}

// GetTagParamsInclude defines parameters for GetTag.
type GetTagParamsInclude string

// UpdateTagParams defines parameters for UpdateTag.
type UpdateTagParams struct {
	// XXSRFTOKEN Anti-CSRF token extracted from the XSRF-TOKEN cookie.
	XXSRFTOKEN XSRFTokenHeader `json:"X-XSRF-TOKEN"`
}

// ListTimespansParams defines parameters for ListTimespans.
type ListTimespansParams struct {
	// Limit Maximum number of items to return per page. Capped at 100 to prevent resource exhaustion.
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Number of items to skip from the beginning (zero-indexed).
	Offset *Offset `form:"offset,omitempty" json:"offset,omitempty"`
}

// CreateTimespanParams defines parameters for CreateTimespan.
type CreateTimespanParams struct {
	// XXSRFTOKEN Anti-CSRF token extracted from the XSRF-TOKEN cookie.
	XXSRFTOKEN XSRFTokenHeader `json:"X-XSRF-TOKEN"`
}

// DeleteTimespanParams defines parameters for DeleteTimespan.
type DeleteTimespanParams struct {
	// XXSRFTOKEN Anti-CSRF token extracted from the XSRF-TOKEN cookie.
	XXSRFTOKEN XSRFTokenHeader `json:"X-XSRF-TOKEN"`
}

// UpdateTimespanParams defines parameters for UpdateTimespan.
type UpdateTimespanParams struct {
	// XXSRFTOKEN Anti-CSRF token extracted from the XSRF-TOKEN cookie.
	XXSRFTOKEN XSRFTokenHeader `json:"X-XSRF-TOKEN"`
}

// AuthCallbackParams defines parameters for AuthCallback.
type AuthCallbackParams struct {
	Code  Code  `form:"code" json:"code"`
	State State `form:"state" json:"state"`
}

// AuthLoginParams defines parameters for AuthLogin.
type AuthLoginParams struct {
	// Redirect Optional application-relative path to return to after successful authentication.
	Redirect *Redirect `form:"redirect,omitempty" json:"redirect,omitempty"`
}

// AuthLogoutParams defines parameters for AuthLogout.
type AuthLogoutParams struct {
	// XXSRFTOKEN Anti-CSRF token extracted from the XSRF-TOKEN cookie.
	XXSRFTOKEN XSRFTokenHeader `json:"X-XSRF-TOKEN"`
}

// UpdateCurrentUserJSONRequestBody defines body for UpdateCurrentUser for application/json ContentType.
type UpdateCurrentUserJSONRequestBody = UpdateUser

// CreateProjectJSONRequestBody defines body for CreateProject for application/json ContentType.
type CreateProjectJSONRequestBody = CreateProject

// UpdateProjectJSONRequestBody defines body for UpdateProject for application/json ContentType.
type UpdateProjectJSONRequestBody = UpdateProject

// CreateTagJSONRequestBody defines body for CreateTag for application/json ContentType.
type CreateTagJSONRequestBody = CreateTag

// UpdateTagJSONRequestBody defines body for UpdateTag for application/json ContentType.
type UpdateTagJSONRequestBody = UpdateTag

// CreateTimespanJSONRequestBody defines body for CreateTimespan for application/json ContentType.
type CreateTimespanJSONRequestBody = CreateTimespan

// UpdateTimespanJSONRequestBody defines body for UpdateTimespan for application/json ContentType.
type UpdateTimespanJSONRequestBody = UpdateTimespan
