// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List projects
	// (GET /projects)
	ListProjects(w http.ResponseWriter, r *http.Request, params ListProjectsParams)
	// Create project
	// (POST /projects)
	CreateProject(w http.ResponseWriter, r *http.Request)
	// Delete project
	// (DELETE /projects/{projectId})
	DeleteProject(w http.ResponseWriter, r *http.Request, projectId ProjectIdPath)
	// Get project
	// (GET /projects/{projectId})
	GetProject(w http.ResponseWriter, r *http.Request, projectId ProjectIdPath, params GetProjectParams)
	// Update project
	// (PATCH /projects/{projectId})
	UpdateProject(w http.ResponseWriter, r *http.Request, projectId ProjectIdPath)
	// Get timeseries stats for a project
	// (GET /projects/{projectId}/stats)
	GetProjectStats(w http.ResponseWriter, r *http.Request, projectId ProjectIdPath, params GetProjectStatsParams)
	// List tags
	// (GET /tags)
	ListTags(w http.ResponseWriter, r *http.Request, params ListTagsParams)
	// Create tag
	// (POST /tags)
	CreateTag(w http.ResponseWriter, r *http.Request)
	// Delete tag
	// (DELETE /tags/{tagId})
	DeleteTag(w http.ResponseWriter, r *http.Request, tagId TagIdPath)
	// Get tag
	// (GET /tags/{tagId})
	GetTag(w http.ResponseWriter, r *http.Request, tagId TagIdPath, params GetTagParams)
	// Update tag
	// (PATCH /tags/{tagId})
	UpdateTag(w http.ResponseWriter, r *http.Request, tagId TagIdPath)
	// List time spans
	// (GET /timespans)
	ListTimespans(w http.ResponseWriter, r *http.Request, params ListTimespansParams)
	// Create time span
	// (POST /timespans)
	CreateTimespan(w http.ResponseWriter, r *http.Request)
	// Delete time span
	// (DELETE /timespans/{timespanId})
	DeleteTimespan(w http.ResponseWriter, r *http.Request, timespanId TimespanIdPath)
	// Get time span
	// (GET /timespans/{timespanId})
	GetTimespan(w http.ResponseWriter, r *http.Request, timespanId TimespanIdPath)
	// Update time span
	// (PATCH /timespans/{timespanId})
	UpdateTimespan(w http.ResponseWriter, r *http.Request, timespanId TimespanIdPath)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// List projects
// (GET /projects)
func (_ Unimplemented) ListProjects(w http.ResponseWriter, r *http.Request, params ListProjectsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create project
// (POST /projects)
func (_ Unimplemented) CreateProject(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete project
// (DELETE /projects/{projectId})
func (_ Unimplemented) DeleteProject(w http.ResponseWriter, r *http.Request, projectId ProjectIdPath) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get project
// (GET /projects/{projectId})
func (_ Unimplemented) GetProject(w http.ResponseWriter, r *http.Request, projectId ProjectIdPath, params GetProjectParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update project
// (PATCH /projects/{projectId})
func (_ Unimplemented) UpdateProject(w http.ResponseWriter, r *http.Request, projectId ProjectIdPath) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get timeseries stats for a project
// (GET /projects/{projectId}/stats)
func (_ Unimplemented) GetProjectStats(w http.ResponseWriter, r *http.Request, projectId ProjectIdPath, params GetProjectStatsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List tags
// (GET /tags)
func (_ Unimplemented) ListTags(w http.ResponseWriter, r *http.Request, params ListTagsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create tag
// (POST /tags)
func (_ Unimplemented) CreateTag(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete tag
// (DELETE /tags/{tagId})
func (_ Unimplemented) DeleteTag(w http.ResponseWriter, r *http.Request, tagId TagIdPath) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get tag
// (GET /tags/{tagId})
func (_ Unimplemented) GetTag(w http.ResponseWriter, r *http.Request, tagId TagIdPath, params GetTagParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update tag
// (PATCH /tags/{tagId})
func (_ Unimplemented) UpdateTag(w http.ResponseWriter, r *http.Request, tagId TagIdPath) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List time spans
// (GET /timespans)
func (_ Unimplemented) ListTimespans(w http.ResponseWriter, r *http.Request, params ListTimespansParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create time span
// (POST /timespans)
func (_ Unimplemented) CreateTimespan(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete time span
// (DELETE /timespans/{timespanId})
func (_ Unimplemented) DeleteTimespan(w http.ResponseWriter, r *http.Request, timespanId TimespanIdPath) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get time span
// (GET /timespans/{timespanId})
func (_ Unimplemented) GetTimespan(w http.ResponseWriter, r *http.Request, timespanId TimespanIdPath) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update time span
// (PATCH /timespans/{timespanId})
func (_ Unimplemented) UpdateTimespan(w http.ResponseWriter, r *http.Request, timespanId TimespanIdPath) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListProjects operation middleware
func (siw *ServerInterfaceWrapper) ListProjects(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListProjectsParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", r.URL.Query(), &params.Offset)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListProjects(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateProject operation middleware
func (siw *ServerInterfaceWrapper) CreateProject(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateProject(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteProject operation middleware
func (siw *ServerInterfaceWrapper) DeleteProject(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "projectId" -------------
	var projectId ProjectIdPath

	err = runtime.BindStyledParameterWithOptions("simple", "projectId", chi.URLParam(r, "projectId"), &projectId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "projectId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteProject(w, r, projectId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetProject operation middleware
func (siw *ServerInterfaceWrapper) GetProject(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "projectId" -------------
	var projectId ProjectIdPath

	err = runtime.BindStyledParameterWithOptions("simple", "projectId", chi.URLParam(r, "projectId"), &projectId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "projectId", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetProjectParams

	// ------------- Optional query parameter "include" -------------

	err = runtime.BindQueryParameter("form", false, false, "include", r.URL.Query(), &params.Include)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "include", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetProject(w, r, projectId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateProject operation middleware
func (siw *ServerInterfaceWrapper) UpdateProject(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "projectId" -------------
	var projectId ProjectIdPath

	err = runtime.BindStyledParameterWithOptions("simple", "projectId", chi.URLParam(r, "projectId"), &projectId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "projectId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateProject(w, r, projectId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetProjectStats operation middleware
func (siw *ServerInterfaceWrapper) GetProjectStats(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "projectId" -------------
	var projectId ProjectIdPath

	err = runtime.BindStyledParameterWithOptions("simple", "projectId", chi.URLParam(r, "projectId"), &projectId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "projectId", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetProjectStatsParams

	// ------------- Required query parameter "metric" -------------

	if paramValue := r.URL.Query().Get("metric"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "metric"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "metric", r.URL.Query(), &params.Metric)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "metric", Err: err})
		return
	}

	// ------------- Optional query parameter "interval" -------------

	err = runtime.BindQueryParameter("form", true, false, "interval", r.URL.Query(), &params.Interval)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "interval", Err: err})
		return
	}

	// ------------- Optional query parameter "granularity" -------------

	err = runtime.BindQueryParameter("form", true, false, "granularity", r.URL.Query(), &params.Granularity)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "granularity", Err: err})
		return
	}

	// ------------- Optional query parameter "timezone" -------------

	err = runtime.BindQueryParameter("form", true, false, "timezone", r.URL.Query(), &params.Timezone)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "timezone", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetProjectStats(w, r, projectId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListTags operation middleware
func (siw *ServerInterfaceWrapper) ListTags(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListTagsParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", r.URL.Query(), &params.Offset)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListTags(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateTag operation middleware
func (siw *ServerInterfaceWrapper) CreateTag(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateTag(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteTag operation middleware
func (siw *ServerInterfaceWrapper) DeleteTag(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "tagId" -------------
	var tagId TagIdPath

	err = runtime.BindStyledParameterWithOptions("simple", "tagId", chi.URLParam(r, "tagId"), &tagId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tagId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteTag(w, r, tagId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetTag operation middleware
func (siw *ServerInterfaceWrapper) GetTag(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "tagId" -------------
	var tagId TagIdPath

	err = runtime.BindStyledParameterWithOptions("simple", "tagId", chi.URLParam(r, "tagId"), &tagId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tagId", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetTagParams

	// ------------- Optional query parameter "include" -------------

	err = runtime.BindQueryParameter("form", false, false, "include", r.URL.Query(), &params.Include)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "include", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetTag(w, r, tagId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateTag operation middleware
func (siw *ServerInterfaceWrapper) UpdateTag(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "tagId" -------------
	var tagId TagIdPath

	err = runtime.BindStyledParameterWithOptions("simple", "tagId", chi.URLParam(r, "tagId"), &tagId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tagId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateTag(w, r, tagId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListTimespans operation middleware
func (siw *ServerInterfaceWrapper) ListTimespans(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListTimespansParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", r.URL.Query(), &params.Offset)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListTimespans(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateTimespan operation middleware
func (siw *ServerInterfaceWrapper) CreateTimespan(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateTimespan(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteTimespan operation middleware
func (siw *ServerInterfaceWrapper) DeleteTimespan(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "timespanId" -------------
	var timespanId TimespanIdPath

	err = runtime.BindStyledParameterWithOptions("simple", "timespanId", chi.URLParam(r, "timespanId"), &timespanId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "timespanId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteTimespan(w, r, timespanId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetTimespan operation middleware
func (siw *ServerInterfaceWrapper) GetTimespan(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "timespanId" -------------
	var timespanId TimespanIdPath

	err = runtime.BindStyledParameterWithOptions("simple", "timespanId", chi.URLParam(r, "timespanId"), &timespanId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "timespanId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetTimespan(w, r, timespanId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateTimespan operation middleware
func (siw *ServerInterfaceWrapper) UpdateTimespan(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "timespanId" -------------
	var timespanId TimespanIdPath

	err = runtime.BindStyledParameterWithOptions("simple", "timespanId", chi.URLParam(r, "timespanId"), &timespanId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "timespanId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateTimespan(w, r, timespanId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/projects", wrapper.ListProjects)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/projects", wrapper.CreateProject)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/projects/{projectId}", wrapper.DeleteProject)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/projects/{projectId}", wrapper.GetProject)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/projects/{projectId}", wrapper.UpdateProject)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/projects/{projectId}/stats", wrapper.GetProjectStats)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/tags", wrapper.ListTags)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/tags", wrapper.CreateTag)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/tags/{tagId}", wrapper.DeleteTag)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/tags/{tagId}", wrapper.GetTag)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/tags/{tagId}", wrapper.UpdateTag)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/timespans", wrapper.ListTimespans)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/timespans", wrapper.CreateTimespan)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/timespans/{timespanId}", wrapper.DeleteTimespan)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/timespans/{timespanId}", wrapper.GetTimespan)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/timespans/{timespanId}", wrapper.UpdateTimespan)
	})

	return r
}

type ListProjectsRequestObject struct {
	Params ListProjectsParams
}

type ListProjectsResponseObject interface {
	VisitListProjectsResponse(w http.ResponseWriter) error
}

type ListProjects200JSONResponse PaginatedProjects

func (response ListProjects200JSONResponse) VisitListProjectsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ListProjects400Response struct {
}

func (response ListProjects400Response) VisitListProjectsResponse(w http.ResponseWriter) error {
	w.WriteHeader(400)
	return nil
}

type CreateProjectRequestObject struct {
	Body *CreateProjectJSONRequestBody
}

type CreateProjectResponseObject interface {
	VisitCreateProjectResponse(w http.ResponseWriter) error
}

type CreateProject201JSONResponse Project

func (response CreateProject201JSONResponse) VisitCreateProjectResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type CreateProject400Response struct {
}

func (response CreateProject400Response) VisitCreateProjectResponse(w http.ResponseWriter) error {
	w.WriteHeader(400)
	return nil
}

type DeleteProjectRequestObject struct {
	ProjectId ProjectIdPath `json:"projectId"`
}

type DeleteProjectResponseObject interface {
	VisitDeleteProjectResponse(w http.ResponseWriter) error
}

type DeleteProject204Response struct {
}

func (response DeleteProject204Response) VisitDeleteProjectResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteProject404Response struct {
}

func (response DeleteProject404Response) VisitDeleteProjectResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

type GetProjectRequestObject struct {
	ProjectId ProjectIdPath `json:"projectId"`
	Params    GetProjectParams
}

type GetProjectResponseObject interface {
	VisitGetProjectResponse(w http.ResponseWriter) error
}

type GetProject200JSONResponse Project

func (response GetProject200JSONResponse) VisitGetProjectResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetProject404Response struct {
}

func (response GetProject404Response) VisitGetProjectResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

type UpdateProjectRequestObject struct {
	ProjectId ProjectIdPath `json:"projectId"`
	Body      *UpdateProjectJSONRequestBody
}

type UpdateProjectResponseObject interface {
	VisitUpdateProjectResponse(w http.ResponseWriter) error
}

type UpdateProject200JSONResponse Project

func (response UpdateProject200JSONResponse) VisitUpdateProjectResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type UpdateProject400Response struct {
}

func (response UpdateProject400Response) VisitUpdateProjectResponse(w http.ResponseWriter) error {
	w.WriteHeader(400)
	return nil
}

type UpdateProject404Response struct {
}

func (response UpdateProject404Response) VisitUpdateProjectResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

type GetProjectStatsRequestObject struct {
	ProjectId ProjectIdPath `json:"projectId"`
	Params    GetProjectStatsParams
}

type GetProjectStatsResponseObject interface {
	VisitGetProjectStatsResponse(w http.ResponseWriter) error
}

type GetProjectStats200JSONResponse ProjectStats

func (response GetProjectStats200JSONResponse) VisitGetProjectStatsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetProjectStats400Response struct {
}

func (response GetProjectStats400Response) VisitGetProjectStatsResponse(w http.ResponseWriter) error {
	w.WriteHeader(400)
	return nil
}

type GetProjectStats404Response struct {
}

func (response GetProjectStats404Response) VisitGetProjectStatsResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

type GetProjectStats422Response struct {
}

func (response GetProjectStats422Response) VisitGetProjectStatsResponse(w http.ResponseWriter) error {
	w.WriteHeader(422)
	return nil
}

type ListTagsRequestObject struct {
	Params ListTagsParams
}

type ListTagsResponseObject interface {
	VisitListTagsResponse(w http.ResponseWriter) error
}

type ListTags200JSONResponse PaginatedTags

func (response ListTags200JSONResponse) VisitListTagsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ListTags400Response struct {
}

func (response ListTags400Response) VisitListTagsResponse(w http.ResponseWriter) error {
	w.WriteHeader(400)
	return nil
}

type CreateTagRequestObject struct {
	Body *CreateTagJSONRequestBody
}

type CreateTagResponseObject interface {
	VisitCreateTagResponse(w http.ResponseWriter) error
}

type CreateTag201JSONResponse Tag

func (response CreateTag201JSONResponse) VisitCreateTagResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type CreateTag400Response struct {
}

func (response CreateTag400Response) VisitCreateTagResponse(w http.ResponseWriter) error {
	w.WriteHeader(400)
	return nil
}

type DeleteTagRequestObject struct {
	TagId TagIdPath `json:"tagId"`
}

type DeleteTagResponseObject interface {
	VisitDeleteTagResponse(w http.ResponseWriter) error
}

type DeleteTag204Response struct {
}

func (response DeleteTag204Response) VisitDeleteTagResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteTag404Response struct {
}

func (response DeleteTag404Response) VisitDeleteTagResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

type GetTagRequestObject struct {
	TagId  TagIdPath `json:"tagId"`
	Params GetTagParams
}

type GetTagResponseObject interface {
	VisitGetTagResponse(w http.ResponseWriter) error
}

type GetTag200JSONResponse Tag

func (response GetTag200JSONResponse) VisitGetTagResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetTag404Response struct {
}

func (response GetTag404Response) VisitGetTagResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

type UpdateTagRequestObject struct {
	TagId TagIdPath `json:"tagId"`
	Body  *UpdateTagJSONRequestBody
}

type UpdateTagResponseObject interface {
	VisitUpdateTagResponse(w http.ResponseWriter) error
}

type UpdateTag200JSONResponse Tag

func (response UpdateTag200JSONResponse) VisitUpdateTagResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type UpdateTag400Response struct {
}

func (response UpdateTag400Response) VisitUpdateTagResponse(w http.ResponseWriter) error {
	w.WriteHeader(400)
	return nil
}

type UpdateTag404Response struct {
}

func (response UpdateTag404Response) VisitUpdateTagResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

type ListTimespansRequestObject struct {
	Params ListTimespansParams
}

type ListTimespansResponseObject interface {
	VisitListTimespansResponse(w http.ResponseWriter) error
}

type ListTimespans200JSONResponse PaginatedTimespans

func (response ListTimespans200JSONResponse) VisitListTimespansResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ListTimespans400Response struct {
}

func (response ListTimespans400Response) VisitListTimespansResponse(w http.ResponseWriter) error {
	w.WriteHeader(400)
	return nil
}

type CreateTimespanRequestObject struct {
	Body *CreateTimespanJSONRequestBody
}

type CreateTimespanResponseObject interface {
	VisitCreateTimespanResponse(w http.ResponseWriter) error
}

type CreateTimespan201JSONResponse Timespan

func (response CreateTimespan201JSONResponse) VisitCreateTimespanResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type CreateTimespan400Response struct {
}

func (response CreateTimespan400Response) VisitCreateTimespanResponse(w http.ResponseWriter) error {
	w.WriteHeader(400)
	return nil
}

type DeleteTimespanRequestObject struct {
	TimespanId TimespanIdPath `json:"timespanId"`
}

type DeleteTimespanResponseObject interface {
	VisitDeleteTimespanResponse(w http.ResponseWriter) error
}

type DeleteTimespan204Response struct {
}

func (response DeleteTimespan204Response) VisitDeleteTimespanResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteTimespan404Response struct {
}

func (response DeleteTimespan404Response) VisitDeleteTimespanResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

type GetTimespanRequestObject struct {
	TimespanId TimespanIdPath `json:"timespanId"`
}

type GetTimespanResponseObject interface {
	VisitGetTimespanResponse(w http.ResponseWriter) error
}

type GetTimespan200JSONResponse Timespan

func (response GetTimespan200JSONResponse) VisitGetTimespanResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetTimespan404Response struct {
}

func (response GetTimespan404Response) VisitGetTimespanResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

type UpdateTimespanRequestObject struct {
	TimespanId TimespanIdPath `json:"timespanId"`
	Body       *UpdateTimespanJSONRequestBody
}

type UpdateTimespanResponseObject interface {
	VisitUpdateTimespanResponse(w http.ResponseWriter) error
}

type UpdateTimespan200JSONResponse Timespan

func (response UpdateTimespan200JSONResponse) VisitUpdateTimespanResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type UpdateTimespan400Response struct {
}

func (response UpdateTimespan400Response) VisitUpdateTimespanResponse(w http.ResponseWriter) error {
	w.WriteHeader(400)
	return nil
}

type UpdateTimespan404Response struct {
}

func (response UpdateTimespan404Response) VisitUpdateTimespanResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// List projects
	// (GET /projects)
	ListProjects(ctx context.Context, request ListProjectsRequestObject) (ListProjectsResponseObject, error)
	// Create project
	// (POST /projects)
	CreateProject(ctx context.Context, request CreateProjectRequestObject) (CreateProjectResponseObject, error)
	// Delete project
	// (DELETE /projects/{projectId})
	DeleteProject(ctx context.Context, request DeleteProjectRequestObject) (DeleteProjectResponseObject, error)
	// Get project
	// (GET /projects/{projectId})
	GetProject(ctx context.Context, request GetProjectRequestObject) (GetProjectResponseObject, error)
	// Update project
	// (PATCH /projects/{projectId})
	UpdateProject(ctx context.Context, request UpdateProjectRequestObject) (UpdateProjectResponseObject, error)
	// Get timeseries stats for a project
	// (GET /projects/{projectId}/stats)
	GetProjectStats(ctx context.Context, request GetProjectStatsRequestObject) (GetProjectStatsResponseObject, error)
	// List tags
	// (GET /tags)
	ListTags(ctx context.Context, request ListTagsRequestObject) (ListTagsResponseObject, error)
	// Create tag
	// (POST /tags)
	CreateTag(ctx context.Context, request CreateTagRequestObject) (CreateTagResponseObject, error)
	// Delete tag
	// (DELETE /tags/{tagId})
	DeleteTag(ctx context.Context, request DeleteTagRequestObject) (DeleteTagResponseObject, error)
	// Get tag
	// (GET /tags/{tagId})
	GetTag(ctx context.Context, request GetTagRequestObject) (GetTagResponseObject, error)
	// Update tag
	// (PATCH /tags/{tagId})
	UpdateTag(ctx context.Context, request UpdateTagRequestObject) (UpdateTagResponseObject, error)
	// List time spans
	// (GET /timespans)
	ListTimespans(ctx context.Context, request ListTimespansRequestObject) (ListTimespansResponseObject, error)
	// Create time span
	// (POST /timespans)
	CreateTimespan(ctx context.Context, request CreateTimespanRequestObject) (CreateTimespanResponseObject, error)
	// Delete time span
	// (DELETE /timespans/{timespanId})
	DeleteTimespan(ctx context.Context, request DeleteTimespanRequestObject) (DeleteTimespanResponseObject, error)
	// Get time span
	// (GET /timespans/{timespanId})
	GetTimespan(ctx context.Context, request GetTimespanRequestObject) (GetTimespanResponseObject, error)
	// Update time span
	// (PATCH /timespans/{timespanId})
	UpdateTimespan(ctx context.Context, request UpdateTimespanRequestObject) (UpdateTimespanResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// ListProjects operation middleware
func (sh *strictHandler) ListProjects(w http.ResponseWriter, r *http.Request, params ListProjectsParams) {
	var request ListProjectsRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListProjects(ctx, request.(ListProjectsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListProjects")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListProjectsResponseObject); ok {
		if err := validResponse.VisitListProjectsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateProject operation middleware
func (sh *strictHandler) CreateProject(w http.ResponseWriter, r *http.Request) {
	var request CreateProjectRequestObject

	var body CreateProjectJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateProject(ctx, request.(CreateProjectRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateProject")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateProjectResponseObject); ok {
		if err := validResponse.VisitCreateProjectResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteProject operation middleware
func (sh *strictHandler) DeleteProject(w http.ResponseWriter, r *http.Request, projectId ProjectIdPath) {
	var request DeleteProjectRequestObject

	request.ProjectId = projectId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteProject(ctx, request.(DeleteProjectRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteProject")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteProjectResponseObject); ok {
		if err := validResponse.VisitDeleteProjectResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetProject operation middleware
func (sh *strictHandler) GetProject(w http.ResponseWriter, r *http.Request, projectId ProjectIdPath, params GetProjectParams) {
	var request GetProjectRequestObject

	request.ProjectId = projectId
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetProject(ctx, request.(GetProjectRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetProject")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetProjectResponseObject); ok {
		if err := validResponse.VisitGetProjectResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateProject operation middleware
func (sh *strictHandler) UpdateProject(w http.ResponseWriter, r *http.Request, projectId ProjectIdPath) {
	var request UpdateProjectRequestObject

	request.ProjectId = projectId

	var body UpdateProjectJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateProject(ctx, request.(UpdateProjectRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateProject")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UpdateProjectResponseObject); ok {
		if err := validResponse.VisitUpdateProjectResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetProjectStats operation middleware
func (sh *strictHandler) GetProjectStats(w http.ResponseWriter, r *http.Request, projectId ProjectIdPath, params GetProjectStatsParams) {
	var request GetProjectStatsRequestObject

	request.ProjectId = projectId
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetProjectStats(ctx, request.(GetProjectStatsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetProjectStats")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetProjectStatsResponseObject); ok {
		if err := validResponse.VisitGetProjectStatsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListTags operation middleware
func (sh *strictHandler) ListTags(w http.ResponseWriter, r *http.Request, params ListTagsParams) {
	var request ListTagsRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListTags(ctx, request.(ListTagsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListTags")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListTagsResponseObject); ok {
		if err := validResponse.VisitListTagsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateTag operation middleware
func (sh *strictHandler) CreateTag(w http.ResponseWriter, r *http.Request) {
	var request CreateTagRequestObject

	var body CreateTagJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateTag(ctx, request.(CreateTagRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateTag")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateTagResponseObject); ok {
		if err := validResponse.VisitCreateTagResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteTag operation middleware
func (sh *strictHandler) DeleteTag(w http.ResponseWriter, r *http.Request, tagId TagIdPath) {
	var request DeleteTagRequestObject

	request.TagId = tagId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteTag(ctx, request.(DeleteTagRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteTag")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteTagResponseObject); ok {
		if err := validResponse.VisitDeleteTagResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetTag operation middleware
func (sh *strictHandler) GetTag(w http.ResponseWriter, r *http.Request, tagId TagIdPath, params GetTagParams) {
	var request GetTagRequestObject

	request.TagId = tagId
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetTag(ctx, request.(GetTagRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetTag")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetTagResponseObject); ok {
		if err := validResponse.VisitGetTagResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateTag operation middleware
func (sh *strictHandler) UpdateTag(w http.ResponseWriter, r *http.Request, tagId TagIdPath) {
	var request UpdateTagRequestObject

	request.TagId = tagId

	var body UpdateTagJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateTag(ctx, request.(UpdateTagRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateTag")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UpdateTagResponseObject); ok {
		if err := validResponse.VisitUpdateTagResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListTimespans operation middleware
func (sh *strictHandler) ListTimespans(w http.ResponseWriter, r *http.Request, params ListTimespansParams) {
	var request ListTimespansRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListTimespans(ctx, request.(ListTimespansRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListTimespans")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListTimespansResponseObject); ok {
		if err := validResponse.VisitListTimespansResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateTimespan operation middleware
func (sh *strictHandler) CreateTimespan(w http.ResponseWriter, r *http.Request) {
	var request CreateTimespanRequestObject

	var body CreateTimespanJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateTimespan(ctx, request.(CreateTimespanRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateTimespan")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateTimespanResponseObject); ok {
		if err := validResponse.VisitCreateTimespanResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteTimespan operation middleware
func (sh *strictHandler) DeleteTimespan(w http.ResponseWriter, r *http.Request, timespanId TimespanIdPath) {
	var request DeleteTimespanRequestObject

	request.TimespanId = timespanId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteTimespan(ctx, request.(DeleteTimespanRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteTimespan")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteTimespanResponseObject); ok {
		if err := validResponse.VisitDeleteTimespanResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetTimespan operation middleware
func (sh *strictHandler) GetTimespan(w http.ResponseWriter, r *http.Request, timespanId TimespanIdPath) {
	var request GetTimespanRequestObject

	request.TimespanId = timespanId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetTimespan(ctx, request.(GetTimespanRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetTimespan")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetTimespanResponseObject); ok {
		if err := validResponse.VisitGetTimespanResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateTimespan operation middleware
func (sh *strictHandler) UpdateTimespan(w http.ResponseWriter, r *http.Request, timespanId TimespanIdPath) {
	var request UpdateTimespanRequestObject

	request.TimespanId = timespanId

	var body UpdateTimespanJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateTimespan(ctx, request.(UpdateTimespanRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateTimespan")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UpdateTimespanResponseObject); ok {
		if err := validResponse.VisitUpdateTimespanResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}
