/* tslint:disable */
/* eslint-disable */
/**
 * Inundated
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateTag
 */
export interface CreateTag {
    /**
     * 
     * @type {string}
     * @memberof CreateTag
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof CreateTag
     */
    color: string;
}

/**
 * Check if a given object implements the CreateTag interface.
 */
export function instanceOfCreateTag(value: object): value is CreateTag {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('color' in value) || value['color'] === undefined) return false;
    return true;
}

export function CreateTagFromJSON(json: any): CreateTag {
    return CreateTagFromJSONTyped(json, false);
}

export function CreateTagFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateTag {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'color': json['color'],
    };
}

export function CreateTagToJSON(json: any): CreateTag {
    return CreateTagToJSONTyped(json, false);
}

export function CreateTagToJSONTyped(value?: CreateTag | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'color': value['color'],
    };
}

