when:
  - event: pull_request
  - event: push
    branch: main

services:
  - name: dind
    image: docker:29.3.0-dind-rootless
    backend_options: &backops
      kubernetes:
        tolerations:
          - key: amd64
            value: "true"
            effect: PreferNoSchedule
        nodeSelector:
          kubernetes.io/arch: amd64

steps:
  - name: lint
    image: golangci/golangci-lint:v2.11.2-alpine
    commands:
      - golangci-lint run ./...
    when:
      - path:
          exclude: 
            - frontend/**
    backend_options: *backops
    depends_on: []

  - name: test
    image: golang:1.25.5-alpine
    commands:
      - go test -coverprofile=coverage.out ./...
      - go tool cover -func=coverage.out
    environment:
      DOCKER_HOST: tcp://docker:2376
      # TESTCONTAINERS_RYUK_DISABLED: "true"
    when:
      - path:
          exclude: 
            - frontend/**
    backend_options: *backops
    depends_on:
      - dind

  - name: build
    image: golang:1.25.5-alpine
    commands:
      - go build -o inundated cmd/server/main.go
    when:
      - path:
          exclude: 
            - frontend/**
    backend_options: *backops
    depends_on:
      - lint
