when:
  - event: pull_request
  - event: push
    branch: main
  - event: push
    branch: ci-test

steps:
  - name: lint
    image: golangci/golangci-lint:v2.11.2-alpine
    commands:
      - golangci-lint run ./...
    when:
      - path:
          exclude: 
            - frontend/**
    backend_options:
      kubernetes:
        tolerations:
          - key: amd64
            value: "true"
            effect: PreferNoSchedule
        nodeSelector:
          kubernetes.io/arch: amd64



  - name: test
    image: golang:1.25.5-alpine
    commands:
      - go test -coverprofile=coverage.out ./...
      - go tool cover -func=coverage.out
    when:
      - path:
          exclude: 
            - frontend/**

  - name: test
    image: golang:1.25.5-alpine
    commands:
      - go build -o inundated cmd/server/main.go
    when:
      - path:
          exclude: 
            - frontend/**
