when:
  - event: pull_request
  - event: push
    branch: main

variables:
  backend_options: &backend_options
    kubernetes:
      tolerations:
        - key: amd64
          value: "true"
          effect: PreferNoSchedule
      nodeSelector:
        kubernetes.io/arch: amd64

services:
  - name: kubedock
    image: ghcr.io/joyrex2001/kubedock:0.20.3
    commands:
      - /usr/local/bin/kubedock server --disable-dind --reverse-proxy --node-selector=kubernetes.io/arch=amd64
    backend_options: 
      <<: *backend_options
      kubernetes:
        serviceAccountName: kubedock

steps:
  - name: lint
    image: golangci/golangci-lint:v2.11.2-alpine
    commands:
      - golangci-lint run ./...
    when:
      - path:
          exclude: 
            - frontend/**
    backend_options: *backend_options
    depends_on: []

  - name: test
    image: golang:1.25.5-alpine
    commands:
      - go test -coverprofile=coverage.out ./...
      - go tool cover -func=coverage.out
    when:
      - path:
          exclude: 
            - frontend/**
    environment:
      DOCKER_HOST: tcp://kubedock:2475
      TESTCONTAINERS_RYUK_DISABLED: "true"
      # TESTCONTAINERS_CHECKS_DISABLE: "true"
    backend_options: *backend_options
    depends_on: []

  - name: build
    image: golang:1.25.5-alpine
    commands:
      - go build -o inundated cmd/server/main.go
    when:
      - path:
          exclude: 
            - frontend/**
    backend_options: *backend_options
    depends_on: []
