when:
  - event: pull_request
    path:
      include: 
        - frontend/**
        - .woodpecker/**
  - event: push
    branch: main
    path:
      include: 
        - frontend/**
        - .woodpecker/**

variables:
  backend_options: &backend_options
    kubernetes:
      tolerations:
        - key: amd64
          value: "true"
          effect: PreferNoSchedule
      nodeSelector:
        kubernetes.io/arch: amd64

steps:
  - name: install
    image: node:24-alpine
    directory: frontend
    commands:
      - npm ci
    backend_options: *backend_options

  - name: lint
    image: node:24-alpine
    directory: frontend
    commands:
      - npm run lint
    backend_options: *backend_options
    depends_on: 
      - install

  - name: test
    image: node:24-alpine
    directory: frontend
    commands:
      - npm run test
    backend_options: *backend_options
    depends_on: 
      - install

  - name: build
    image: node:24-alpine
    directory: frontend
    commands:
      - npm run build
    backend_options: *backend_options
    depends_on: 
      - install
