when:
  - event: push
    branch: main
  - event: push
    branch: ci-test

# depends_on:
#   - ci-api
#   - ci-frontend

steps:
  - name: build-and-push
    image: woodpeckerci/plugin-docker-buildx:6.0.4
    settings:
      registry: git.larssonoliver.com
      repo: git.larssonoliver.com/oliver/inundated
      tags:
        - latest
      dockerfile: build/Dockerfile
      platforms: linux/amd64,linux/arm64
